site_name: Jacob Hashicorp Book
site_description: "Jacob's Hashicorp Tutorial Book"
site_author: "Jacob Xi"
copyright: "Copyright &copy; 2021-9999 Jacob Xi"
site_url: "https://chao-xi.github.io/jxhashicorpbook/"

plugins:
  - search # necessary for search to work
  - awesome-pages

nav:
  - 'Welcome': "index.md"
  - '私密信息管理利器Vault':
    - '1 私密信息管理利器 HashiCorp Vault——简介': 'vault/1vault_intro.md'
    - '2 私密信息管理利器 HashiCorp Vault——启动和读写': 'vault/2vault_start.md'
    - '3 私密信息管理利器 HashiCorp Vault——Secret Engine': 'vault/3vault_secretengine.md'
    - '4 私密信息管理利器 HashiCorp Vault——验证和授权': 'vault/4vault_auth.md'
    - '5 私密信息管理利器 HashiCorp Vault——部署': 'vault/5vault_deploy.md'
    - '6 私密信息管理利器 HashiCorp Vault——REST API': 'vault/6vault_api.md'
    - '7 密钥管理神器之 Vault 集群搭建': 'vault/7vault_impl.md'
    - '8 K8S与Vault集成，进行Secret管理': 'vault/8vault_k8s.md'
    - '9 使用 Docker 和 Traefik 搭建 Vault': 'vault/9vault_docker.md'
    - '10 使用 Vault + Cert Manager 管理 Kubernetes 集群中的数字证书': 'vault/10vault_cm.md'
    - '11 云原生更安全的密文管理 Vault on ACK': 'vault/13vault_ack_cloud.md'
    - '12 Kubernetes 的 secret 并不是真正的 secret': 'vault/14K8s_secret.md'
  - 'Vault on K8S':
    - 'L0 在 Kubernetes 上部署 Vault': 'vault1/0k8s_vault.md'
    - 'L1 Hashcorp Vault 基础使用教程': 'vault1/1Vault_basic.md'
    - 'L2 在 Kubernetes 读取 Vault 中的机密信息': 'vault1/2vault_k8s.md'
    - 'L3 透过 Vault 定期 rotate credentials': 'vault1/3vault_rotate.md'
    - 'L4 Vault 与 Kubernetes 的深度整合': 'vault1/4vault_int_k8s.md'
  - 'Hashicorp Certified Vault Associate':
    - 'L1 Vault Associate: Introduction': 'vault2/1vaba_intro.md'
    - 'L2 Authentication and Policies': 'vault2/2vaba_auth_poly.md'
    - 'L3 Vault Token': 'vault2/3vaba_token.md'
    - 'L4 Using Secrets Engines': 'vault2/4vaba_engines.md'
    - 'L5 Using Vault Leases': 'vault2/5vaba_lease.md'
  - 'Installing Configuring Vault':
    - 'L1 HashiCorp Vault Overview and Installation': 'vault3/1intro.md'
    - 'L2 Vault a Deployment Model': 'vault3/2dev_model.md'
    - 'L3 Deploying Vault Server': 'vault3/3deploy_valut.md'
    - 'L4 Managing Encryption and Seal Keys': 'vault3/4encryption_key.md'
    - 'L5 Configuring High Availability': 'vault3/5conf_ha.md'
    - 'L6 Configuring Basic Authentication': 'vault3/6basic_auth.md'
    - 'L7 Using Secrets Engines': 'vault3/7vaba_secret_engine.md'
    - 'L8 Configuring Auditing and Monitoring': 'vault3/8vaba_monitor.md'
  - 'Managing Access and Secrets(Adv.)':
    - 'L1 Secrets in HashiCorp Vault Introduction': 'vault4/1mag_vt_intro.md'
    - 'L2 Installing and Configuring Authentication Methods': 'vault4/2vt_auth_method.md'
    - 'L3 Working with Tokens': 'vault4/3vt_token.md'
    - 'L4 Managing Secrets with Secrets Engines': 'vault4/3vt_token.md'
  - 'Integrating with DevOps':
    - 'L1 Accessing Secrets in CI/CD Pipelines': 'vault5/1cicd_pipeline.md'
    - 'L2 Securely Introducing Clients Using Vault Agent': 'vault5/2vault_agent.md'
    - 'L3 Integrating Vault with Terraform & Nomad': 'vault5/3vault_tf_nd.md'
    - 'L4 Integrating Vault with Consul': 'vault5/4vault_consul.md'
    - 'L5 Authenticating Using Cloud Machine Identity': 'vault5/5vault_cloud.md'
    - 'L6 Integrating Vault with Kubernetes': 'vault5/6vault_k8s.md'
  - 'Ops on Vault Server':
    - 'L1 Managing the Encryption Key': 'vault6/1encrypt_key.md'
    - 'L2 Managing the Storage Backend': 'vault6/2bak_storage.md'
    - 'L3 Managing the Vault Server during an Incident': 'vault6/3incident.md'
    - 'L4 Managing External Plugins and Server Upgrades': 'vault6/4Plugins.md'
  - 'Terraform Tools':
    - 'L1 使用Terragrunt优化Terraform代码': 'tfm1/1Terragrunt.md'
    - 'L2 基础设施即代码 - 使用Terraform创建AWS EC2实例并部署Jenkins服务': 'tfm1/2TMF_JENKINS.md'

repo_url: https://github.com/Chao-Xi/jxhashicorpbook.git
repo_name: "jxhashicorpbook"

theme: 
  language: zh
  name: 'material'
  include_sidebar: true
  logo: 'images/logo.png'
  favicon: 'images/logo.png'
  feature:
    tabs: false
  palette:
    primary: 'blue grey'
    accent: 'blue greay'
  i18n:
    prev: 'Previous'
    next: 'Next'